/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CardType = IDL.Variant({
  'Amex' : IDL.Null,
  'Visa' : IDL.Null,
  'Mastercard' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'balance' : IDL.Int,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
});
export const Card = IDL.Record({
  'id' : IDL.Nat,
  'maskedNumber' : IDL.Text,
  'owner' : IDL.Principal,
  'cardType' : CardType,
  'expiry' : IDL.Text,
});
export const TransactionCategory = IDL.Variant({
  'Food' : IDL.Null,
  'Health' : IDL.Null,
  'Entertainment' : IDL.Null,
  'Shopping' : IDL.Null,
  'Other' : IDL.Null,
  'Transport' : IDL.Null,
});
export const CategorySpending = IDL.Record({
  'category' : TransactionCategory,
  'amount' : IDL.Int,
});
export const MonthlySpending = IDL.Record({
  'month' : IDL.Text,
  'amount' : IDL.Int,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'read' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const TransactionStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'status' : TransactionStatus,
  'date' : Time,
  'receiverId' : IDL.Principal,
  'category' : TransactionCategory,
  'amount' : IDL.Int,
  'senderId' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCard' : IDL.Func([IDL.Text, IDL.Text, CardType], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCards' : IDL.Func([], [IDL.Vec(Card)], ['query']),
  'getCurrentMonthSpending' : IDL.Func(
      [],
      [IDL.Vec(CategorySpending)],
      ['query'],
    ),
  'getLast6MonthsSpending' : IDL.Func(
      [],
      [IDL.Vec(MonthlySpending)],
      ['query'],
    ),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAllNotificationsAsRead' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedDemoData' : IDL.Func([], [], []),
  'sendMoney' : IDL.Func([IDL.Principal, IDL.Int, TransactionCategory], [], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CardType = IDL.Variant({
    'Amex' : IDL.Null,
    'Visa' : IDL.Null,
    'Mastercard' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'balance' : IDL.Int,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
  });
  const Card = IDL.Record({
    'id' : IDL.Nat,
    'maskedNumber' : IDL.Text,
    'owner' : IDL.Principal,
    'cardType' : CardType,
    'expiry' : IDL.Text,
  });
  const TransactionCategory = IDL.Variant({
    'Food' : IDL.Null,
    'Health' : IDL.Null,
    'Entertainment' : IDL.Null,
    'Shopping' : IDL.Null,
    'Other' : IDL.Null,
    'Transport' : IDL.Null,
  });
  const CategorySpending = IDL.Record({
    'category' : TransactionCategory,
    'amount' : IDL.Int,
  });
  const MonthlySpending = IDL.Record({
    'month' : IDL.Text,
    'amount' : IDL.Int,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'read' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const TransactionStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'status' : TransactionStatus,
    'date' : Time,
    'receiverId' : IDL.Principal,
    'category' : TransactionCategory,
    'amount' : IDL.Int,
    'senderId' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCard' : IDL.Func([IDL.Text, IDL.Text, CardType], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCards' : IDL.Func([], [IDL.Vec(Card)], ['query']),
    'getCurrentMonthSpending' : IDL.Func(
        [],
        [IDL.Vec(CategorySpending)],
        ['query'],
      ),
    'getLast6MonthsSpending' : IDL.Func(
        [],
        [IDL.Vec(MonthlySpending)],
        ['query'],
      ),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAllNotificationsAsRead' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedDemoData' : IDL.Func([], [], []),
    'sendMoney' : IDL.Func(
        [IDL.Principal, IDL.Int, TransactionCategory],
        [],
        [],
      ),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };