/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Card {
  'id' : bigint,
  'maskedNumber' : string,
  'owner' : Principal,
  'cardType' : CardType,
  'expiry' : string,
}
export type CardType = { 'Amex' : null } |
  { 'Visa' : null } |
  { 'Mastercard' : null };
export interface CategorySpending {
  'category' : TransactionCategory,
  'amount' : bigint,
}
export interface MonthlySpending { 'month' : string, 'amount' : bigint }
export interface Notification {
  'id' : bigint,
  'owner' : Principal,
  'read' : boolean,
  'message' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export interface Transaction {
  'id' : bigint,
  'status' : TransactionStatus,
  'date' : Time,
  'receiverId' : Principal,
  'category' : TransactionCategory,
  'amount' : bigint,
  'senderId' : Principal,
}
export type TransactionCategory = { 'Food' : null } |
  { 'Health' : null } |
  { 'Entertainment' : null } |
  { 'Shopping' : null } |
  { 'Other' : null } |
  { 'Transport' : null };
export type TransactionStatus = { 'Failed' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface UserProfile {
  'balance' : bigint,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCard' : ActorMethod<[string, string, CardType], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCards' : ActorMethod<[], Array<Card>>,
  'getCurrentMonthSpending' : ActorMethod<[], Array<CategorySpending>>,
  'getLast6MonthsSpending' : ActorMethod<[], Array<MonthlySpending>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAllNotificationsAsRead' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedDemoData' : ActorMethod<[], undefined>,
  'sendMoney' : ActorMethod<
    [Principal, bigint, TransactionCategory],
    undefined
  >,
  'updateProfile' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];