/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Card {
    id: bigint;
    maskedNumber: string;
    owner: Principal;
    cardType: CardType;
    expiry: string;
}
export type Time = bigint;
export interface MonthlySpending {
    month: string;
    amount: bigint;
}
export interface Notification {
    id: bigint;
    owner: Principal;
    read: boolean;
    message: string;
    timestamp: Time;
}
export interface CategorySpending {
    category: TransactionCategory;
    amount: bigint;
}
export interface UserProfile {
    balance: bigint;
    name: string;
    createdAt: Time;
    email: string;
}
export interface Transaction {
    id: bigint;
    status: TransactionStatus;
    date: Time;
    receiverId: Principal;
    category: TransactionCategory;
    amount: bigint;
    senderId: Principal;
}
export enum CardType {
    Amex = "Amex",
    Visa = "Visa",
    Mastercard = "Mastercard"
}
export enum TransactionCategory {
    Food = "Food",
    Health = "Health",
    Entertainment = "Entertainment",
    Shopping = "Shopping",
    Other = "Other",
    Transport = "Transport"
}
export enum TransactionStatus {
    Failed = "Failed",
    Completed = "Completed",
    Pending = "Pending"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCard(maskedNumber: string, expiry: string, cardType: CardType): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCards(): Promise<Array<Card>>;
    getCurrentMonthSpending(): Promise<Array<CategorySpending>>;
    getLast6MonthsSpending(): Promise<Array<MonthlySpending>>;
    getNotifications(): Promise<Array<Notification>>;
    getTransactions(): Promise<Array<Transaction>>;
    getUnreadNotificationCount(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markAllNotificationsAsRead(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    seedDemoData(): Promise<void>;
    sendMoney(receiver: Principal, amount: bigint, category: TransactionCategory): Promise<void>;
    updateProfile(name: string, email: string): Promise<void>;
}
import type { Card as _Card, CardType as _CardType, CategorySpending as _CategorySpending, Time as _Time, Transaction as _Transaction, TransactionCategory as _TransactionCategory, TransactionStatus as _TransactionStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCard(arg0: string, arg1: string, arg2: CardType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCard(arg0, arg1, to_candid_CardType_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCard(arg0, arg1, to_candid_CardType_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCards(): Promise<Array<Card>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCards();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCards();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentMonthSpending(): Promise<Array<CategorySpending>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentMonthSpending();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentMonthSpending();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLast6MonthsSpending(): Promise<Array<MonthlySpending>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLast6MonthsSpending();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLast6MonthsSpending();
            return result;
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return result;
        }
    }
    async getTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadNotificationCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadNotificationCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadNotificationCount();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markAllNotificationsAsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsAsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsAsRead();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async seedDemoData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedDemoData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedDemoData();
            return result;
        }
    }
    async sendMoney(arg0: Principal, arg1: bigint, arg2: TransactionCategory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMoney(arg0, arg1, to_candid_TransactionCategory_n23(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMoney(arg0, arg1, to_candid_TransactionCategory_n23(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1);
            return result;
        }
    }
}
function from_candid_CardType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CardType): CardType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Card_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Card): Card {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_CategorySpending_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CategorySpending): CategorySpending {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionCategory_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionCategory): TransactionCategory {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionStatus): TransactionStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    maskedNumber: string;
    owner: Principal;
    cardType: _CardType;
    expiry: string;
}): {
    id: bigint;
    maskedNumber: string;
    owner: Principal;
    cardType: CardType;
    expiry: string;
} {
    return {
        id: value.id,
        maskedNumber: value.maskedNumber,
        owner: value.owner,
        cardType: from_candid_CardType_n11(_uploadFile, _downloadFile, value.cardType),
        expiry: value.expiry
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    category: _TransactionCategory;
    amount: bigint;
}): {
    category: TransactionCategory;
    amount: bigint;
} {
    return {
        category: from_candid_TransactionCategory_n16(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TransactionStatus;
    date: _Time;
    receiverId: Principal;
    category: _TransactionCategory;
    amount: bigint;
    senderId: Principal;
}): {
    id: bigint;
    status: TransactionStatus;
    date: Time;
    receiverId: Principal;
    category: TransactionCategory;
    amount: bigint;
    senderId: Principal;
} {
    return {
        id: value.id,
        status: from_candid_TransactionStatus_n21(_uploadFile, _downloadFile, value.status),
        date: value.date,
        receiverId: value.receiverId,
        category: from_candid_TransactionCategory_n16(_uploadFile, _downloadFile, value.category),
        amount: value.amount,
        senderId: value.senderId
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Amex: null;
} | {
    Visa: null;
} | {
    Mastercard: null;
}): CardType {
    return "Amex" in value ? CardType.Amex : "Visa" in value ? CardType.Visa : "Mastercard" in value ? CardType.Mastercard : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Food: null;
} | {
    Health: null;
} | {
    Entertainment: null;
} | {
    Shopping: null;
} | {
    Other: null;
} | {
    Transport: null;
}): TransactionCategory {
    return "Food" in value ? TransactionCategory.Food : "Health" in value ? TransactionCategory.Health : "Entertainment" in value ? TransactionCategory.Entertainment : "Shopping" in value ? TransactionCategory.Shopping : "Other" in value ? TransactionCategory.Other : "Transport" in value ? TransactionCategory.Transport : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Failed: null;
} | {
    Completed: null;
} | {
    Pending: null;
}): TransactionStatus {
    return "Failed" in value ? TransactionStatus.Failed : "Completed" in value ? TransactionStatus.Completed : "Pending" in value ? TransactionStatus.Pending : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CategorySpending>): Array<CategorySpending> {
    return value.map((x)=>from_candid_CategorySpending_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Card>): Array<Card> {
    return value.map((x)=>from_candid_Card_n9(_uploadFile, _downloadFile, x));
}
function to_candid_CardType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CardType): _CardType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionCategory_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionCategory): _TransactionCategory {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CardType): {
    Amex: null;
} | {
    Visa: null;
} | {
    Mastercard: null;
} {
    return value == CardType.Amex ? {
        Amex: null
    } : value == CardType.Visa ? {
        Visa: null
    } : value == CardType.Mastercard ? {
        Mastercard: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionCategory): {
    Food: null;
} | {
    Health: null;
} | {
    Entertainment: null;
} | {
    Shopping: null;
} | {
    Other: null;
} | {
    Transport: null;
} {
    return value == TransactionCategory.Food ? {
        Food: null
    } : value == TransactionCategory.Health ? {
        Health: null
    } : value == TransactionCategory.Entertainment ? {
        Entertainment: null
    } : value == TransactionCategory.Shopping ? {
        Shopping: null
    } : value == TransactionCategory.Other ? {
        Other: null
    } : value == TransactionCategory.Transport ? {
        Transport: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
